name: gempush

on:
  push:
    branches:
      - publish

jobs:
  build:
    name: Publish gem
    uses: dawidd6/action-publish-gem@v1
    with:
      api_key: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
      github_token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
