name: gempush

on:
  push:
    branches:
      - publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-publish-gem@v1.2.0
      - name: Publish gem
        with:
          api_key: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
          github_token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
